version: '3.8'
services:
  db:
    container_name: vote-docker
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '4002:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local